language: ruby
rvm:
  - 2.5
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - bundle exec jekyll doctor
  - bundle exec jekyll build
#  - bundle exec htmlproofer ./_site --check-html --disable-external
