title: Unoffical ACC
description: >- # this means to ignore newlines until "baseurl:"
  Central repository for Adobe Campaign Classic packages for you to download and import with ease!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://floriancourgey.github.io/unofficialacc
permalink: /:title

# custom manifest.json
manifest:
  name: "Unoffical ACC"
  short_name: "Unoffical ACC"
  theme_color: "#2196f3"
  background_color: "#2196f3"
  display: "browser"
  scope: "/"
  start_url: "/"


disqus:
  shortname: floriancourgey

gtm:

# paginate plugin
paginate: 10
paginate_path: "/page-:num/"

collections:
  authors:
    output: true
  packages:
    output: true

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Florian Courgey"
  - scope:
      path: ""
      type: "packages"
    values:
      layout: "post"
      author: "Florian Courgey"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Florian Courgey"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# algolia plugin
algolia:
  application_id:
  index_name:     jekyll
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(content)
      - collection
      - tags

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - htmlproofer
